# -*- coding: utf-8 -*-
"""pyprograms.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f4_5n-ZPjlVihuMT9GfXEKWNip4mQWKt
"""

n=int(input("Enter the number of elements"))
x=[]
for i in range(n):
  y=input("enter elements")
  x.append(y)
x.sort()
print(y)
print(s)

x=["the", "the","car"]
s=set(x)
print(s)
x=list(s)
print(x)

n=int(input("enter no. of numbers"))
x=[]
for i in range (n):
  y=input("enter elements:")
  x.append(y)
z=max(x)
print(x)
print("Largest number:",z)

fruits=["apple","orange"]
desserts=["cake", "pie"]

for fruit in fruits:
  for dessert in desserts:
    print(f"{fruit} {dessert}")

number=int(input("Enter the number:"))
if number>0:
  print("the number is positive")
  if number %5==0:
    print("the number is a multiple of 5")
  else:
    print("number is not a multiple of 5")
elif number==0:
    print("number is zero")
else:
  print("Number is a negative number")

x=int(1,2,3,4,5)
for x in x:
  for y in x:
    print(x,y)

for i in range(1,11):
  for j in range (1,11):
    print (f'{i}*{j}={i*j}')
  if j==10:
    print("-"*10)

num_rows = 5

for i in range(1, num_rows + 1):

  for j in range(1, i + 1):
    print(j, end="")

  print()

